### ISSUE TITLE
[homeassistant.core] Error doing job: SSL handshake failed

### ISSUE THREAD

**Issue by doubleugk** [ynot123/LMS_Controls#20]
After changing the config (Sec.B8) The PI doesn't bring up the web interface anymore. In the logs I find the following message. Any clue how to solve this issue?
2019-07-30 22:45:22 ERROR (MainThread) [homeassistant.core] Error doing job: SSL handshake failed
Traceback (most recent call last):
  File "uvloop/sslproto.pyx", line 500, in uvloop.loop.SSLProtocol._on_handshake_complete
  File "uvloop/sslproto.pyx", line 484, in uvloop.loop.SSLProtocol._do_handshake
  File "/usr/local/lib/python3.7/ssl.py", line 774, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: HTTP_REQUEST] http request (_ssl.c:1076)

**Comment by ynot123** [comment]
Once you make those changes and restart, your web interface can now be accessed using the internet based url rather than a local ip.  As an example something like this:  https://yourdomain.duckdns.org/states
